export const TOKEN_KEY = 'TOKEN_KEY';
export const AUTH_HEADER = 'Bearer';
export const clientID = 'DRV00NONW023ZREMUEGK2VHCWO1NBXWQCH5THXWDIJ3UJZN4';
export const clientSecret = '5P5BJN0D55K1IKPR52UJF0PICDID3BLVVUTYKGLJ13REXZZH';